name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger parent repository update
        run: |
          curl -X POST https://api.github.com/repos/DOUS3L/submodule-test-parent/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u smallstepman:${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "arst" }}'
